---
- name: Install Apache on Ubuntu
  hosts: ubuntu, centos
  become: yes
  tasks:
   
    - name: Install Apache on Ubuntu
      tags: ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache service on Ubuntu
      tags: ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
    
    - name: Stop UFW service
      tags: ubuntu
      service:
        name: ufw
        state: stopped
      when: ansible_distribution == "Ubuntu"
       
    - name: install httpd and php package
      tags: cent
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Rocky"
     
    - name: Start httpd service on Rocky
      tags: cent
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Rocky"
    
    - name: Firewall Regel hinzufügen
      tags: cent
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
      when: ansible_distribution == "Rocky"
      
    - name: Neustart Firewalld
      tags: cent
      service:
        name: firewalld
        state: restarted
      when: ansible_distribution == "Rocky"
      
    - name: Standardwebseite austauschen
      tags: cent
      copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
      when: ansible_distribution == "Rocky"
   
    - name: change e-mail address for admin
      tags: cent
      lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "Rocky"
      register: httpd
     
    - name: restart httpd (CentOS)
      tags: apache,centos,httpd
      service:
       name: httpd
       state: restarted
      when: 
        - httpd.changed
        - ansible_distribution == "Rocky"
      
      
        

      
     