---
- name: Install Apache on Ubuntu
  hosts: centos
  become: yes
  tasks:

   - name: install httpd package
     dnf:
       name: httpd
       state: absent
     when: ansible_distribution == "Rocky"
 
   - name: add php support for apache
     dnf:
       name: php
       state: absent
     when: ansible_distribution == "Rocky"
