---
- name: Install Apache on Ubuntu
  hosts: ubuansi
  become: yes
  roles:
     - removeApache
 
   
    
 # command mit tags nur für Ubuntu: ansible-playbook --tags ubuntu --ask-become-pass remove_apache.yml   
