---
- name: update or distupgrade
  hosts: all
  become: yes
  tasks:
   

    - name: install updates (Rocky)
      tags: update
      dnf:
       update_only: yes
       update_cache: yes
      when: ansible_distribution == "Rocky"
 
    - name: install updates (Ubuntu, Debian)
      tags: update
      apt:
       upgrade: yes
       update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian', 'Linux Mint']
      
      
    - name: install updates dist-upgrade
      tags: dist
      apt:
       upgrade: dist
       update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian', 'Linux Mint']
   
     
   