---
- name: Variablen mit groupvars und hostvars
  hosts: dns
  
  
  
  vars_prompt:
    - name: Host
      prompt: Bitte Hostnamen eingeben
      private: false
  
   
  
  tasks:
    - name: Suche und ergänze Zeile in der Konfigurationsdatei
      lineinfile:
        path: /home/torsten/testzonen/master.testzone
        regexp: '^{{Host}}\.vreden\.home'
        line: '{{Host}}.vreden.home'
        state: present
      become: true