  - name: restart_apache
    tags: centos,httpd
    service:
     name: httpd
     state: restarted
  
  - name: restart_firewalld
    tags: centos,httpd
    service:
     name: firewalld
     state: restarted
      